# Generated by Django 4.0 on 2023-08-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clients', '0002_log_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comment', models.TextField(verbose_name='комментарий')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='log',
            name='date_attempt',
            field=models.DateTimeField(verbose_name='дата и время последней попытки'),
        ),
        migrations.AlterField(
            model_name='log',
            name='response_server',
            field=models.CharField(max_length=250, verbose_name='ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='log',
            name='state',
            field=models.CharField(max_length=50, verbose_name='статус попытки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='letter',
            field=models.TextField(verbose_name='тело письма'),
        ),
        migrations.AlterField(
            model_name='message',
            name='theme',
            field=models.CharField(max_length=100, verbose_name='тема письма'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True, verbose_name='время рассылки')),
                ('period', models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=30, verbose_name='периодичность рассылки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('done', 'Завершена')], max_length=30, verbose_name='статус рассылки')),
                ('client', models.ManyToManyField(to='clients.Client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Код пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='newsletter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.newsletter', verbose_name='рассылка'),
            preserve_default=False,
        ),
    ]
