# Generated by Django 4.0 on 2023-08-25 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clients.newsletter', verbose_name='рассылка'),
        ),
    ]
