# Generated by Django 4.0 on 2023-08-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_message_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.message', verbose_name='сообщение'),
            preserve_default=False,
        ),
    ]
