# Generated by Django 4.2.4 on 2023-08-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='time',
            field=models.TimeField(verbose_name='время рассылки'),
        ),
    ]
