# Generated by Django 4.0 on 2023-08-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_newsletter_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'permissions': [('manager_site_newsletter', 'Менеджер')], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
