# Generated by Django 4.0 on 2023-08-29 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.user', verbose_name='Пользователь (Создатель)'),
            preserve_default=False,
        ),
    ]
